#!/vendor/bin/sh

sleep 5

echo -e 'AT+GOOGSETNV="UL3.Cap.Phych.supp_of_fdpch",0,"01,00,00,00"\r
AT+GOOGSETNV="UL3.Cap.Phych.supp_of_Efdpch",0,"01,00,00,00"\r
AT+GOOGSETNV="UL3.Cap.Phych.supp_ul_dtx",0,"00"\r
AT+GOOGSETNV="UL3.Cap.Phych.slotFormat4",0,"00,00,00,00"\r
AT+GOOGSETNV="UL3.Cap.Multi.supp_IRAT PS HO to E-UTRA",0,"01"\r
AT+GOOGSETNV="UL3.Cap.MultiCellSupport_DC_HSDPA",0,"01"\r
AT+GOOGSETNV="UL3.Etc.FastDormancyT323Rel8Support",0,"01,00,00,00"\r

AT+GOOGSETNV="UECAPA_INTRA_FREQ_SI_ACQ_FOR_HO",0,"01"\r
AT+GOOGSETNV="UECAPA_INTER_FREQ_SI_ACQ_FOR_HO",0,"01"\r
AT+GOOGSETNV="UECAPA_UTRAN_SI_ACQ_FOR_HO",0,"01"\r
AT+GOOGSETNV="UECAPA_PDCP_ROHC_PROFILES",3,"00"\r

AT+GOOGSETNV="UECAPA_REL10_FOURLAYER_TM3TM4",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_ORIG_FOURLAYER_TM3TM4",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_CA_INDEX",0,"01,00,00,00"\r
AT+GOOGSETNV="UECAPA_REL10_MIMO_CAPA_DL",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_MIMO_CAPA_UL",0,"02"\r
AT+GOOGSETNV="UECAPA_REL10_MODIFIED_MPR_BEHAVIOR",0,"00,00,00,C0"\r
AT+GOOGSETNV="UECAPA_REL10_FGI103",0,"01"\r

AT+GOOGSETNV="UECAPA_REL12_EXTENDED_MAX_MEASID_SUPPORT",0,"01"\r

AT+GOOGSETNV="UECAPA_REL14_DIFF_FALLBACKCOMB",0,"01"\r

AT+GOOGSETNV="NR.CONFIG.MODE",0,"01"\r
AT+GOOGSETNV="NR.ENDC.MODE",0,"11"\r
AT+GOOGSETNV="DS.NR.CONFIG.MODE",0,"01"\r
AT+GOOGSETNV="DS.NR.ENDC.MODE",0,"11"\r

AT+GOOGSETNV="NASU.NR.CONFIG.MODE",0,"01"\r
AT+GOOGSETNV="DS.NASU.NR.CONFIG.MODE",0,"01"\r

AT+GOOGSETNV="!NRCAPA.Switch.DssFeature",0,"01"\r
AT+GOOGSETNV="!NRCAPA.Gen.DynamicPowerSharing",0,"01"\r

AT+GOOGSETNV="PSS.AIMS.DYNAMIC_OPERATORSPEC_FLAG",0,"01"\r
AT+GOOGSETNV="PSS.AIMS.ENABLE.RPORT-InVia-Header",0,"01"\r

AT+GOOGSETNV="PSS.AIMS.Payload-EVS",0,"6E"\r
AT+GOOGSETNV="PSS.AIMS.Audio.Media.RS",0,"00,00,00,00"\r
AT+GOOGSETNV="PSS.AIMS.Audio.Media.RR",0,"20,03,00,00"\r

AT+GOOGSETNV="DS.PSS.AIMS.Payload-EVS",0,"6E"\r
AT+GOOGSETNV="DS.PSS.AIMS.Audio.Media.RS",0,"00,00,00,00"\r
AT+GOOGSETNV="DS.PSS.AIMS.Audio.Media.RR",0,"20,03,00,00"\r

AT+GOOGSETNV="DS.PSS.AIMS.ENABLE.RPORT-InVia-Header",0,"01"\r
AT+GOOGSETNV="DS.PSS.AIMS.DYNAMIC_OPERATORSPEC_FLAG",0,"01"\r
AT+GOOGSETNV="DS.PSS.AIMS.ACCESSTYPE.SUPPORT",0,"00"\r

AT+GOOGSETNV="!NRSM.MsSupportLocalAddrTFTRequest",0,"01"\r

AT+GOOGSETNV="!SAEL3.PCO_IPV4_MTU_MAX_SIZE",0,"DC,05"\r
AT+GOOGSETNV="!SAEL3.IMS_PCO_IPV4_MTU_MAX_SIZE",0,"DC,05"\r
AT+GOOGSETNV="!SAEL3.EXTPCO_REQUEST",0,"01"\r
AT+GOOGSETNV="!SAEL3.ENABLE_GUARD_T_FOR_WAIT_ATTACHAPN",0,"01"\r
AT+GOOGSETNV="!SAEL3.DISABLE_IPV4_MTU_IN_PCO",0,"01"\r
AT+GOOGSETNV="!SAEL3.Dual_IP_PDP",0,"01"\r
AT+GOOGSETNV="!SAEL3.PDN_SM_PDU_DN_REQ_CONTAINER",0,"00"\r
AT+GOOGSETNV="!SAEL3_DS.PCO_IPV4_MTU_MAX_SIZE",0,"DC,05"\r
AT+GOOGSETNV="!SAEL3_DS.IMS_PCO_IPV4_MTU_MAX_SIZE",0,"DC,05"\r
AT+GOOGSETNV="!SAEL3_DS.EXTPCO_REQUEST",0,"01"\r
AT+GOOGSETNV="!SAEL3_DS.ENABLE_GUARD_T_FOR_WAIT_ATTACHAPN",0,"01"\r
AT+GOOGSETNV="!SAEL3_DS.DISABLE_IPV4_MTU_IN_PCO",0,"01"\r

AT+GOOGSETNV="HCOMMON.MM.LCS_VA_capability",0,"01"\r

AT+GOOGSETNV="NASL3.MM.umts_fdd",0,"01"\r
AT+GOOGSETNV="NASL3.MM.GeranFeaturePack1",0,"01"\r
AT+GOOGSETNV="NASL3.MM.gea_algorithms",1,"00"\r
AT+GOOGSETNV="NASL3.SM.NW Initiated Secondary PDP Activation Support",0,"01"\r
AT+GOOGSETNV="ds_NASL3.MM.umts_fdd",0,"01"\r
AT+GOOGSETNV="ds_NASL3.MM.GeranFeaturePack1",0,"01"\r
AT+GOOGSETNV="ds_NASL3.MM.gea_algorithms",1,"00"\r

AT+CFUN=0\rAT+CFUN=1\r' > /dev/umts_router

echo -e 'AT+GOOGSETNV="PSS.AIMS.Payload-AMRWB",0,"64"\r
AT+GOOGSETNV="PSS.AIMS.Payload-AMRWB",1,"FF"\r
AT+GOOGSETNV="PSS.AIMS.Payload-AMRNB",1,"FF"\r
AT+GOOGSETNV="PSS.AIMS.Payload-DTMF",0,"65"\r
AT+GOOGSETNV="PSS.AIMS.Payload-DTMF.WB",0,"6B"\r
AT+GOOGSETNV="PSS.AIMS.Audio.Media.RR",0,"9C,04,00,00"\r

AT+GOOGSETNV="DS.PSS.AIMS.Payload-AMRWB",0,"64"\r
AT+GOOGSETNV="DS.PSS.AIMS.Payload-AMRWB",1,"FF"\r
AT+GOOGSETNV="DS.PSS.AIMS.Payload-AMRNB",1,"FF"\r
AT+GOOGSETNV="DS.PSS.AIMS.Payload-DTMF",0,"65"\r
AT+GOOGSETNV="DS.PSS.AIMS.Payload-DTMF.WB",0,"6B"\r
AT+GOOGSETNV="DS.PSS.AIMS.Audio.Media.RR",0,"9C,04,00,00"\r

AT+CFUN=0\rAT+CFUN=1\r' > /dev/umts_router
log -t VoLTE-Config "VoLTE Script finished successfully."
